In [23]:
import os
import numpy as np
import librosa
import librosa.display
import torch
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [24]:
dataset_path = "../Data/features_30_sec.csv"

data = pd.read_csv(dataset_path)

spectral_features = [
    "chroma_stft_mean", "chroma_stft_var",
    "spectral_centroid_mean", "spectral_centroid_var",
    "rolloff_mean", "rolloff_var"
]
rhythmic_features = ["tempo"]
mfcc_features = [
    "mfcc1_mean", "mfcc1_var",
    "mfcc2_mean", "mfcc2_var",
    "mfcc3_mean", "mfcc3_var"
]

selected_features = spectral_features + rhythmic_features + mfcc_features

X = data[selected_features]
y = data["label"]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [42]:
knn = KNeighborsClassifier(n_neighbors=14)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
score = knn.score(X_test, y_test)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Score: ", score)
print("Confusion matrix: ", conf_matrix)
print("Class report: ", class_report)

Score:  0.5366666666666666
Confusion matrix:  [[15  0  4  4  0  1  1  0  3  2]
 [ 0 29  0  0  0  0  0  0  0  1]
 [ 4  2 17  3  0  3  0  0  0  1]
 [ 0  0  1 16  3  1  2  5  1  1]
 [ 0  0  1  7  8  0  3  6  4  1]
 [ 4  1  4  3  0 17  0  1  0  0]
 [ 2  0  1  5  0  0 20  0  0  2]
 [ 0  1  2  2  4  0  0 19  2  0]
 [ 3  0  1  3  6  0  0  1 15  1]
 [ 1  0  7  6  2  0  5  2  2  5]]
Class report:                precision    recall  f1-score   support

       blues       0.52      0.50      0.51        30
   classical       0.88      0.97      0.92        30
     country       0.45      0.57      0.50        30
       disco       0.33      0.53      0.41        30
      hiphop       0.35      0.27      0.30        30
        jazz       0.77      0.57      0.65        30
       metal       0.65      0.67      0.66        30
         pop       0.56      0.63      0.59        30
      reggae       0.56      0.50      0.53        30
        rock       0.36      0.17      0.23        30

    accuracy